### ISSUE TITLE
2021.1.18填写ID下载图片后为0张图片是什么原因

### ISSUE THREAD

**Issue by 251371029** [JasonkayZK/weiboPicDownloader#3]
15号下载的时候批量下载正常，除了某个用户下载为0张图片，现在全都是0张

**Comment by JasonkayZK** [comment]
微博返回的日期格式变化了，解析的日期都是1970年的。所以导致在判断日期区间时，结果都未包括进来，输出的当然就是0张啦！
目前修复中！

**Comment by JasonkayZK** [comment]
问题在v1.1.2版本已修复！
