### ISSUE TITLE
这个是什么问题呀？

### ISSUE THREAD

**Issue by ririliu** [JasonkayZK/weiboPicDownloader#5]
![图片](https://user-images.githubusercontent.com/30514728/121339438-0d716000-c951-11eb-8bc0-df93b0502d30.png)

这个是什么问题呀？

**Comment by JasonkayZK** [comment]
估计是Electron版本又更新了，有的API不支持了；

**Comment by ririliu** [comment]
你用的是多少版本？我可以指定用你的那个版本吗？

**Comment by JasonkayZK** [comment]
比较尴尬的是，package-lock.json 没提交，我也忘了我的版本了，擦；

**Comment by JasonkayZK** [comment]
我先尝试修复一下看一下；

**Comment by ririliu** [comment]
没想到跑这个比跑个java应用麻烦...

**Comment by JasonkayZK** [comment]
> 没想到跑这个比跑个java应用麻烦...

这是必然的，你可以看看Electron官方有多少Issue没解决了；
我当时写这个也是各种环境问题、网络问题；
这也是我弃坑的原因……

**Comment by ririliu** [comment]
照理说如果是依赖库的问题，就用当时的版本就行了，版本号也可以从时间推断下，比如年初的electron版本

**Comment by JasonkayZK** [comment]
理论上是这样的…；

**Comment by ririliu** [comment]
如果我要指定版本应该怎么操作？

**Comment by JasonkayZK** [comment]
修改package.json；

**Comment by ririliu** [comment]
我看有现在里面有"electron": "^2.0.4" 这配置呢

**Comment by ririliu** [comment]
核心的代码都在src/main/index.js 里面吗？

**Comment by JasonkayZK** [comment]
是的，爬虫的核心代码就在`src/main/index.js`里面，代码其实挺简单的；

另外，我的博客有这个代码逻辑的总结，可以看一下：

[手把手教你使用Electron开发新浪微博免登录图片下载器](https://jasonkayzk.github.io/2020/11/04/%E6%89%8B%E6%8A%8A%E6%89%8B%E6%95%99%E4%BD%A0%E4%BD%BF%E7%94%A8Electron%E5%BC%80%E5%8F%91%E6%96%B0%E6%B5%AA%E5%BE%AE%E5%8D%9A%E5%85%8D%E7%99%BB%E5%BD%95%E5%9B%BE%E7%89%87%E4%B8%8B%E8%BD%BD%E5%99%A8/)

具体为什么过了半年，直接无法运行，我也是无语…；

不过我最近在用Golang重写这里的东西；

**Comment by ririliu** [comment]
我看看用java写个试试，反正我也不需要GUI，就命令行能跑就行了

**Comment by JasonkayZK** [comment]
是的，可以；
目前我就在用Go重写这个命令行工具；

微博爬虫的关键就是：`containerid就是"107603" + uid`
其他的挺简单的；

**Comment by ririliu** [comment]
基本可以用了，去掉了不必要的sleep，使用多线程下载文件，增加一些异常重试机制，公司的网络环境下载一个2千多张照片的微博耗时不到5分钟，之前用你发布的版本耗时1个多小时😂

**Comment by JasonkayZK** [comment]
我这个为了防止恶意爬虫，仅用于学习Electron用的，所以用的单线程；
能用就行
