### ISSUE TITLE
每条微博超过9张图后面的图片不会下载

### ISSUE THREAD

**Issue by CCMonkeyss** [JasonkayZK/weiboPicDownloader#7]
谢谢作者的程序，帮我下载了不少图片，
我发现单条微博超过9张图片的话，
（客户端在第9张图上会显示+x）
9张后的图片不会下载，
我想可能是需要一个展开的动作，才能看到后续图片的地址，
能请作者教一下解决思路吗？
谢谢你。

**Comment by JasonkayZK** [comment]
这个仓库已经不再维护了，你可以 fork 这个仓库自行实现逻辑。

这里记录了开发的思路，供你参考：

- [手把手教你使用Electron开发新浪微博免登录图片下载器](https://jasonkayzk.github.io/2020/11/04/%E6%89%8B%E6%8A%8A%E6%89%8B%E6%95%99%E4%BD%A0%E4%BD%BF%E7%94%A8Electron%E5%BC%80%E5%8F%91%E6%96%B0%E6%B5%AA%E5%BE%AE%E5%8D%9A%E5%85%8D%E7%99%BB%E5%BD%95%E5%9B%BE%E7%89%87%E4%B8%8B%E8%BD%BD%E5%99%A8/)

**Comment by CCMonkeyss** [comment]
好的，谢谢你，我再试试
